Detailed Readme
Moniepoint/dart-flow pull request #26
Opened 2024-04-07 13:46 UTC by abiodundotdev

Added a detailed readme

2024-04-07 21:42 UTC, donpaul120 requested changes

2024-04-07 21:42 UTC, donpaul120 commented on README.md
> +
No RetryPolicy example uses a ```decorrelatedJitter```

2024-04-07 21:42 UTC, donpaul120 commented on README.md
> +    flow((collector) => collector.emit(1, 2, 3))
The example here can be very misleading , the emit function only takes a single argument and not multiple arguments.

2024-04-08 05:51 UTC, abiodundotdev commented on README.md
> +
Updated

2024-04-08 07:38 UTC, merged